### ISSUE TITLE
Upgrading to 0.3.1 from 0.2.0

### ISSUE THREAD

**Issue by wan54** [ForgeRock/appAuthHelper#12]
Hi,

After upgrading to 0.3.1 from 0.2.0 the helper does not initiate a call to the authorization endpoint anymore upon calling AppAuthHelper.init.

Looked through the README and the configuration looks the same except the addition of `extras`

This is my init:

```
AppAuthHelper.init({
	clientId,
	authorizationEndpoint,
	tokenEndpoint,
	revocationEndpoint,
	endSessionEndpoint,
	userInfoEndpoint,
	scopes,
	resourceServers,
	oidc,
	redirectUri,
	serviceWorkerUri,
	extras: { queryParams },

	async tokensAvailableHandler(claims) {
		console.log('>>> claims', claims);
	},
});
```

**Comment by jakefeasel** [comment]
Be sure you are calling AppAuthHelper.getTokens() within the promise that is return from the init function, like so:

```
    AppAuthHelper.init({
      //...
    }).then(function () {
        AppAuthHelper.getTokens();
    });
```

I see that I need to update the readme to make this more obvious.

**Comment by wan54** [comment]
Yes, that's how I done it in 0.2.0.

```
await AppAuthHelper.init({...});
await AppAuthHelper.getTokens();
```

**Comment by wan54** [comment]
So, the redirect_uri example also was updated as part of 0.3.1 I think. 

Added `window.TRUSTED_ORIGIN = document.location.origin;` and the auth endpoint is now called.

**Comment by wan54** [comment]
I'm reopening as the redirection back to the auth provider when login is required is not happening.

**Console log for 0.3.1:**

```
Potential authorization request  http://localhost:9000/oauthcallback {state: "A5HJuOkAEW", error: "login_required"} A5HJuOkAEW undefined login_required

Delivering authorization response
```

The login page hosted in AS is not displayed, stays on the client page

**Console log for 0.2.0:**

```
Potential authorization request  http://localhost:9000/oauthcallback {state: "joKbZ6yJo3", error: "login_required"} joKbZ6yJo3 undefined login_required

Delivering authorization response

Making a request to  AuthorizationRequest {crypto: DefaultCrypto, usePkce: true, clientId: "webapp", redirectUri: "http://localhost:9000/oauthcallback", scope: "members:me", …} 
https://localhost:9031/as/authorization.oauth2?redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Foauthcallback&client_id=webapp&response_type=code&state=CuRidD0n8F&scope=members%3Ame&code_challenge=HwzE0U3yLfqYaydzxhjKTDuIpwbUX_vqrt8uMK4h3-0&code_challenge_method=S256

Navigated to https://localhost:9031/as/authorization.oauth2?redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Foauthcallback&client_id=webapp&response_type=code&state=CuRidD0n8F&scope=members%3Ame&code_challenge=HwzE0U3yLfqYaydzxhjKTDuIpwbUX_vqrt8uMK4h3-0&code_challenge_method=S256
```

And the login page hosted in AS is displayed

**Comment by jakefeasel** [comment]
I have discovered the issue. In 0.2.0, any error response from the authorization endpoint would be interpreted as "interaction required"; here's where that logic existed: https://github.com/ForgeRock/appAuthHelper/blob/v0.2.0/appAuthHelperFetchTokens.js#L114

In 0.3.0 (and 0.3.1), I changed the error handling logic changed to be more specific. Now, it's looking specifically for the "interaction_required" error value: https://github.com/ForgeRock/appAuthHelper/blob/v0.3.1/appAuthHelperFetchTokens.js#L26

It looks like your AS is producing "login_required", which is a legit error code. From what I'm seeing [here](https://openid.net/specs/openid-connect-core-1_0.html#AuthError), There could be some other possible values too. So, basically this is a bug. I'll adjust the error handling logic so that it returns to the 0.2.0 behavior. Thanks!
